pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building DevOps Capstone Application...'
                sh 'docker --version'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh 'echo Tests completed'
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully!'
        }

        failure {
            echo 'Build failed!'
        }
    }
}