apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-service
  namespace: devops

spec:
  type: LoadBalancer

  selector:
    app: devops-capstone-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000